services:
  - type: web
    name: ai-doc-analyzer-backend
    runtime: node
    buildCommand: cd server && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
  - type: web
    name: ai-doc-analyzer-frontend
    runtime: node
    buildCommand: cd client && npm install && npm run build
    autoDeploy: true